sudo: false

os: linux

language: go

go:
  - 1.7
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  # Disable go1.5 vendoring so Godep handling is used.
  - GO15VENDOREXPERIMENT="0"

before_install: cd cli

script:
  - ../scripts/test-go-fmt.sh
