sudo: false

language: go

matrix:
  include:
    - go: 1.7
      os: linux
    - go: 1.7
      os: osx
    - go: tip
      os: linux
    - go: tip
      os: osx
  fast_finish: true
  allow_failures:
  - go: tip

install:
  - cd cli && godep restore -v

script:
  - ./bin/test-go-fmt.sh
